/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        File input = new File(Objects.requireNonNull(App.class.getClassLoader()
                .getResource("input.txt")).getFile());

        System.out.println("--- Day 1: Chronal Calibration ---");

        System.out.println();

        System.out.println("Part One - Resulting frequency :");
        System.out.println(getResultingFrequency(input));

        System.out.println();

        System.out.println("Part Two - First frequency reached twice :");
        System.out.println(getFirstFrequencyReachedTwice(input));
    }

    private static int getResultingFrequency(File input) {

        int result = 0;

        try (Scanner scanner = new Scanner(input)){
            while (scanner.hasNextLine()) {
                String line = scanner.nextLine();
                int number = Integer.parseInt(line.substring(1));
                result += line.startsWith("+") ? number : -number;
            }
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }

        return result;
    }

    private static int getFirstFrequencyReachedTwice(File input) {

        List<Integer> resultList = new ArrayList<>();
        int result = 0;
        boolean foundFlag = false;

        while(!foundFlag) {

            try (Scanner scanner = new Scanner(input)) {
                while (scanner.hasNextLine()) {
                    String line = scanner.nextLine();
                    int number = Integer.parseInt(line.substring(1));
                    result += line.startsWith("+") ? number : -number;

                    if (!resultList.isEmpty() && resultList.contains(result)) {
                        foundFlag = true;
                        break;
                    }

                    resultList.add(result);
                }
            } catch (FileNotFoundException e) {
                e.printStackTrace();
            }
        }

        return result;
    }
}
