/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.io.File;
import java.io.FileNotFoundException;
import java.util.*;

public class Day2 {

    public static void main(String[] args) {
        File input = new File(Objects.requireNonNull(Day2.class.getClassLoader()
                .getResource("input.txt")).getFile());

        System.out.println("--- Day 2: Inventory Management System ---");

        System.out.println();

        System.out.println("Part One - The checksum :");
        System.out.println(getChecksum(input));

        System.out.println();

        System.out.println("Part Two - Common letters between the two correct box IDs :");
        System.out.println(getCommonLetters(input));
    }

    private static int getChecksum(File input) {

        int twoTimes = 0;
        int treeTimes = 0;

        try (Scanner scanner = new Scanner(input)){
            while (scanner.hasNextLine()) {
                char[] lineLetters = scanner.nextLine().toCharArray();
                Map<Character, Integer> commonLettersMap = new HashMap<>();
                boolean twoTimesFound = false;
                boolean treeTimesFound = false;
                for (char letter : lineLetters) {
                    if (commonLettersMap.containsKey(letter)) {
                        commonLettersMap.put(letter, commonLettersMap.get(letter) + 1);
                    } else {
                        commonLettersMap.put(letter, 1);
                    }
                }
                for (int value : commonLettersMap.values()) {
                    if (value == 2) {
                        twoTimesFound = true;
                    }
                    else if (value == 3) {
                        treeTimesFound = true;
                    }
                }
                if (twoTimesFound) {
                    twoTimes++;
                }
                if (treeTimesFound) {
                    treeTimes++;
                }
            }
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }

        return twoTimes*treeTimes;
    }

    private static String getCommonLetters(File input) {

        String result = null;

        try (Scanner scanner = new Scanner(input)) {

            List<String> lineList = new ArrayList<>();
            boolean foundFlag = false;

            while (scanner.hasNextLine() && !foundFlag) {
                String line = scanner.nextLine();

                if (!lineList.isEmpty()) {
                    for (String lineToCompare : lineList) {

                        int differentLettersNumber = 0;
                        int lastIndexOfDifferentChar = 0;

                        for (int index = 0;
                             index < (line.length() <= lineToCompare.length() ? line.length() : lineToCompare.length());
                             index++
                        ) {
                            if (line.charAt(index) != lineToCompare.charAt(index)) {
                                differentLettersNumber++;
                                lastIndexOfDifferentChar = index;
                            }
                        }

                       if (differentLettersNumber == 1) {
                           result = new StringBuilder(line).deleteCharAt(lastIndexOfDifferentChar).toString();
                           foundFlag = true;
                           break;
                       }
                    }
                }

                if (!foundFlag){
                    lineList.add(line);
                }
            }
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }

        return result;
    }
}
